### ISSUE TITLE
.net 8 update

### ISSUE THREAD

**Issue by orosbogdan** [Videogamers0/MGUI#14]
Is there any update planned for the latest version of .NET /monogame ?

**Comment by Videogamers0** [comment]
Upgrading to .net 8.0 is probably trivial. Just change the target framework in the .csproj:

`<TargetFramework>net6.0-windows</TargetFramework>`

to

`<TargetFramework>net8.0-windows</TargetFramework>`

I doubt it would break anything.

As for the latest MonoGame, you can try updating the nuget packages. But one thing you should be aware of is that I was intentionally targeting an older version of `MonoGame.Content.Builder.Task` (version 3.8.0.1641) rather than the latest version, because there was a bug in version 3.8.1.303 that [caused text to render with incorrect letter spacing](https://community.monogame.net/t/incorrect-kerning-when-drawing-text/18213). I'm unsure of if that bug has been fixed by now (it was like 1.5 years ago). A user on the monogame forums put together a useful .gif that shows the differences we were experiencing in text rendering between the different versions:

![alt text](https://community.monogame.net/uploads/default/original/2X/8/833e898e7bedb1362f99b8e47aefe6dce474e5b2.gif)
