### ISSUE TITLE
MGUI ThreadSafety ?

### ISSUE THREAD

**Issue by orosbogdan** [Videogamers0/MGUI#18]
Is MGUI threadsafe by design ? 

Would the following code be threadsafe and work as expected ? 

` MGTextBlock Button_Text = Window.GetElementByName<MGTextBlock>("Button_Text");`
` Task.Run(() => Button_Text.Text = "REERD" );`

**Comment by Videogamers0** [comment]
There is no explicit multi-threading safety. I'd venture a guess that it would work fine in most cases. If you're just planning to use a single background thread then I doubt it'd cause issues. But if you plan to use multiple threads, which may need to modify the same properties concurrently, I'd guess that there could be some issues.

For example, when the `Text` property on an `MGTextBlock` is modified, some computations take place to re-calculate which substrings of the text should go on which line numbers. If thread 1 changed `Text`, and then thread 2 changed `Text` while thread 1 was still recalculating the text lines, and then thread 2 finished calculating the lines before thread 1, it could end up setting the text lines to a value that corresponds to an old `Text`. This scenario is unlikely since it's usually not a very expensive operation, so the threads probably wouldn't interweave those calculations (although I guess it could be expensive if the textblock had a very large amount of text to parse).

Input handling and layout calculations are always processed during `MGDesktop.Update` so those should be unaffected by multi-threading.

Also, I once did run into an issue when running code from a non-STA thread.
0ee22f375bd5100fc49688ac8e1c5b3aec3987d2
I was opening a file browser dialog in response to a button click, but using an `OpenFileDialog` from a non-STA thread was throwing an error. So it's possible that other obscure issues like that could occur with multi-threading.
